### PR TITLE
Add depth license checking management

### PR DESCRIPTION
**Pull request by HerveNivon**
Hi,

Nice to meet you. 

I'm in the process of license validation and your tool was the closest to what I was looking for. It only missed a `depth` option management.

Here it is. I leveraged the `depth` option of `read-installed` package. It is not perfect because sometimes a `npm install` may installed dependencies of your direct dependencies at level 0. Anyway, it still allows filtering of `node_modules`.

I also documented the `start` option. Which I would I love to name `path`.

### CODE REVIEW

**Comment by aruizca** [comment]
@HerveNivon FYI You have merge conflits.

**Comment by aruizca** [comment]
Hi @davglass Is there anything else we can help with to get this merged?

**Comment by HerveNivon** [comment]
I'm not using it anymore. It's unfortunate, but we may lose my PR.

**Comment by davglass** [comment]
Published in `license-checker@25.0.0`

**Comment by aruizca** [comment]
Thanks @davglass 
Could you update the README documentation with the new arguments please?
Cheers

**Comment by davglass** [comment]
Just pushed up `25.0.1` with an updated README.

**Comment by aruizca** [comment]
I think you forgot about the depth option ;-)

**Comment by davglass** [comment]
I didn’t merge it directly, I changed it to `—direct` since it was a `Boolean` and not an actual `Number` depth. It seemed more reasonable to say either give me everything or only my direct dependencies versus an arbitrary depth.

**Comment by aruizca** [comment]
oh I see, thanks!

**Pull request closed without merging**
