### PR TITLE
Remove redundant check for === LICENSE

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by davglass** [comment]
This is not a redundant check, it's an alternative spelling.

**Comment by graingert** [comment]
lol, I didn't spot that sorry!

**Comment by davglass** [comment]
No worries, not the first time it's been called out :)
I probably should add a comment for it..

**Comment by graingert** [comment]
maybe use a regex for the whole thing? `/^(.*\/)?LICEN(S|C)E(\..*)?$/i`

**Pull request closed without merging**
