### PR TITLE
Add `--summary` mode to show a summary with counts of the used licenses

### PR DESCRIPTION
**Pull request by tobilg**

### CODE REVIEW

**Comment by davglass** [comment]
Thanks for this! Can you please add tests? The build failed due to test coverage dropping..

**Comment by tobilg** [comment]
@davglass It's at 100% now.

**Comment by davglass** [comment]
Published in `license-checker@13.1.0`

**Comment by tobilg** [comment]
Thanks a lot for the fast merge & publish!

**Pull request merged**
