### PR TITLE
guess CC0-1.0, upgraded jshint

### PR DESCRIPTION
**Pull request by drewfish**

### CODE REVIEW

**Comment by davglass** [comment]
Can you add a test? This drops coverage..

**Comment by drewfish** [comment]
oh sorry, will add

**Comment by drewfish** [comment]
updated:
```
=============================== Coverage summary ===============================
Statements   : 100% ( 256/256 ), 13 ignored
Branches     : 99.52% ( 209/210 ), 22 ignored
Functions    : 100% ( 32/32 ), 2 ignored
Lines        : 100% ( 256/256 )
================================================================================
```

**Comment by davglass** [comment]
Published in `license-checker@8.0.3`

**Pull request merged**
