### PR TITLE
feat: allow restricting output to specified packages

### PR DESCRIPTION
**Pull request by codepunkt**
Hello everyone and a special hello to @davglass!

Thanks for this amazing package - it helps me not implement a lot of things i'd otherwise have to implement! 👍 

Until now, restricting the generated output to specific packages (and versions) is not possible.
In an environment where a legal department has to check every open source license that is part of a delivered product, the only way to handle this with the current version of `license-checker` is to scan **all** dependencies (including devDependencies).

Using the `--production` switch is not feasible in this scenario, because especially in frontend applications that are built using tooling such as `webpack`, `parcel`, `rollup`, `browserify` or others, the tools unfortunately don't care if a dependency that is included in a build artifact was listed as a or derived from a devDependency or a dependency.

Because the bulk of our builds is done with `webpack`, i'm implementing a webpack plugin that generates a list of packages and versions that are actually part of a build output and would love to use depend on `license-checker` to do the heavy-lifting in regards to checking licenses. To do so, i need a way to restrict the `license-checker` output to specific packages and versions while ignoring the rest.

Another way to deal with this would be to expose a method that can check the license of a single package, but that would involve a lot of refactoring, dealing with `read-installed` and more. I've tried it and it did not look & feel well.

Therefore, i've implemented an additional CLI switch called `--packages` that accepts a semicolon-separated list of package@version identifiers and restricts the output of `license-checker` to these packages. The code changes are minimal because all packages read by `read-installed` are checked and the filtered return value is then restricted to the given packages.

I'm aware that this is not the most performant solution, but i'm perfectly fine with that because i did not have to introduce a lot of changes and `license-checker` is pretty fast regardless.

### CODE REVIEW

**Comment by codepunkt** [comment]
Addendum:
The way i plan to use this in my `webpack` plugin is by simply invoking the cli with the new `--packages` flag, passing in all package versions that are part of the build artifact(s).

I noticed a few things regarding this repository and my pull request:
1. I have not written a test for this functionality, yet. I will do so and add it to this PR.
2. The repository does neither have a `package-lock.json` nor a `yarn.lock`. Would it be okay to commit a `package-lock.json`?
3. The code style is mixed (e.g. single and double quotes) and while `eslint --fix` in `prestest` managed to get rid of a lot of havoc that my prettier setup wreaked, i'm inclined to add `prettier` as a devDependency and include a `.prettierrc` with settings that match the `eslint` ones (standardized quotes, use semicolons, have 4 spaces as indentation etc.). Would that be okay?

**Comment by davglass** [comment]
I don't use the `package-lock.json` in any of my projects, feel free to change that but I'm not a fan of it.

As for prettier, I would likely not accept a patch for that. Just a personal preference and it just mangles things too much for my liking.

**Comment by codepunkt** [comment]
### Code Style
I would definitely recommend having a look at prettier and lint-staged to automatically run code formatting on commit.

This would not mean that the code style that is in this PR at the moment would be the new style. Prettier is configurable, especially in regards to line length. But it would enforce consistent usage quotes & more. I personally can't and wouldn't work without it anymore, especially in teams.

But it's your project so i'm fine with both:
- adding prettier, lint-staged and a config that suits your code style
- convert the code back to the previous syntax structure

### Lockfiles
Speaking of lockfiles like `package-lock.json`, `npm-shrinkwrap.json` or `yarn.lock` - how can you even live without them? I advise all the developers that i coach to never work without them because doing so has caused a lot of pain in the past.

This project has dependencies (and devDependencies) that are listed in `package.json` with caret and tilde modifiers as well as a version wildcard. Usually, when running automated tests or builds in the continuous integration environment of your choice, the workflow is as follows:
1. check out sources
2. npm install
3. run lint, tests, build & more

Npm install, without a lockfile, installs directly from `package.json`. This means that every time your tests run, _any_ new version of the wildcard dependency that was published will be installed and used for your continuous integration. In addition to that, every new minor or patch version will be installed for packages with the caret modifier and every new patch version will be installed for packages with the tilde modifiers.

You test locally with the versions that you have installed, every single CI run might run with completely different versions to every run before.

You __need__ a lockfile to fix versions and not have your continuous integration suddenly fail on you.

**Comment by codepunkt** [comment]
Seems there's no discussion regarding code style, so i'll simply add my changes without changing anything else. Will push that additional commit later today!

**Comment by codepunkt** [comment]
ping @davglass 

can you please merge this and release it as a new version?

**Comment by davglass** [comment]
Thanks for reverting the code style change. Published in `license-checker@20.2.0`

**Comment by codepunkt** [comment]
That's awesome. Thanks to you!

**Pull request merged**
